name: Keep Alive

on:
  workflow_dispatch:
  
  schedule:
    - cron: 0 0 */30 * *

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - name: Keep Alive
        run: date > .github/KEEP
      - name: Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Keep Alive
          skip_dirty_check: false
